version: "3.7"
services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laminarx-web
    container_name: laminarx-web-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laminarx-web

  nginx:
    image: nginx:alpine
    container_name: laminarx-web-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laminarx-web

networks:
  laminarx-web:
    driver: bridge
